# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
   include:
     - master
  paths:
    include:
      - Source/Services/RPSLS.NodePlayer.Api/*
      - azure-pipelines.yml
  


# resources:
#   repositories:
#   - repository: RPSLS
#     type: github
#     name: zenithworks/RockPaperScissorsLizardSpock
#     endpoint: 
    


pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: build
  jobs:
  - job: build_service
    displayName: Build Nodejs Player
    pool:
      vmImage: 'Ubuntu-latest'
    steps:
    - script: |
        pwd
        ls -ltrh        
        cp -r ./Source/Services/RPSLS.NodePlayer.Api .
        cd RPSLS.NodePlayer.Api
        npm install
        npm prune --production
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/RPSLS.NodePlayer.Api'
        artifact: 'NodePlayerService'
        publishLocation: 'pipeline'

  
- stage: deploy
  dependsOn: build
  jobs:
  - deployment: DeployNodeJsPlayer
    displayName: Deploy Nodejs Player
    pool:
      vmImage: 'Ubuntu-latest'    
    environment:
      name:  AppVMs
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              pwd
              ls -ltrh 
              rm -rf NodePlayerService
              mv /home/moala/azagent/_work/1/NodePlayerService .
              pwd
              cd NodePlayerService           
              ls -ltrh
              node index.js

