

trigger:
  branches:
   include:
     - master
  paths:
    include:
      - Source/Services/RPSLS.NodePlayer.Api/*
      - azure-pipelines.yml
  


# resources:
#   repositories:
#   - repository: RPSLS
#     type: github
#     name: zenithworks/RockPaperScissorsLizardSpock
#     endpoint: 
    


pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: build
  jobs:
  - job: build_service
    displayName: Build Nodejs Player
    pool:
      vmImage: 'Ubuntu-latest'
    steps:
    - script: |               
        cp -r ./Source/Services/RPSLS.NodePlayer.Api .
        cd RPSLS.NodePlayer.Api
        npm install
        npm prune --production
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/RPSLS.NodePlayer.Api'
        artifact: 'NodePlayerService'
        publishLocation: 'pipeline'

  
- stage: deploy
  dependsOn: build
  jobs:
  - deployment: DeployNodeJsPlayer
    displayName: Deploy Nodejs Player
    pool:
      vmImage: 'Ubuntu-latest'    
    environment:
      name:  AppVMs
      resourceType: VirtualMachine
      tags: prod
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |              
              ps -ef | grep index.js | grep -v grep | awk '{print $2}' | xargs kill
              rm -rf NodePlayerService              
              mv /home/moala/azagent/_work/1/NodePlayerService .       
              cd NodePlayerService
              nohup node index.js >> logs_nodejsservice.txt &

