# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

# resources:
#   repositories:
#   - repository: RPSLS
#     type: github
#     name: zenithworks/RockPaperScissorsLizardSpock
#     endpoint: 
    


pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: build
  jobs:
  - job: Install_node
    displayName: Install node
    pool:
      vmImage: 'Ubuntu-latest'
    steps:
    - script: |
        pwd
        ls -ltrh
    
- stage: deploy
  dependsOn: build
  jobs:
  - deployment: DeployNodeJsPlayer
    displayName: Deploy Nodejs Player
    pool:
      vmImage: 'Ubuntu-latest'    
    environment:
      name:  AppVMs
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              pwd
              cd ~/myapp2                            
              ls -ltrh              
              node index.js
          - script: echo exiting...


